version: 0.2

phases:
  install:
    commands:
      # Update libs
      - apt-get update
      # Headless Chrome
      - apt-get install -y fonts-liberation libasound2 libnspr4 libnss3 libx11-xcb1 xdg-utils libxss1 libappindicator1 libindicator7
      - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - dpkg -i google-chrome*.deb
  pre_build:
    commands: 
      # - npm i aws-sdk
      # - aws codeartifact login --tool npm --repository AngularNodeModule --domain angular-ci-lib --domain-owner 756430146363 
      - npm install
      - npm run test:ci
  build:
    commands:
      - npm run build
  # post_build:
  #   commands:
  #     - aws s3 sync ./dist/angular-devops s3://angular-devops-production --acl 'public-read' --delete

# 成品檔案位置(build的結果)
artifacts:
  files:
    - '**/*'
  base-directory: 'dist/TestCI'